### ISSUE TITLE
Add a PR stack and relevant review stack deployment settings as part of the set up

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi-pequod/pequod-mlc-stackmgmt#2]
I'd need to plan this out, but it should be possible to create a stack using the Pulumi Cloud API directly and then set up the deployment settings to make it work as a template for the review stacks, then copy some settings to the PR stack config.

I think that could be a good way of showing the review stacks easily

**Comment by MitchellGerdisch** [comment]
The StackSettings now sets review stack settings on the stack created by NPW (i.e. the dev stack).
And manages things so it doesn't try to manage deployment settings like it does for other stacks.
Fixed by https://github.com/pulumi-pequod/pequod-mlc-stackmgmt/pull/15 and https://github.com/pulumi-pequod/pequod-mlc-stackmgmt/pull/14

**Comment by MitchellGerdisch** [comment]
backed out https://github.com/pulumi-pequod/pequod-mlc-stackmgmt/pull/15 for now.
The settings will account for things if review stacks are manually enabled but won't automatically configure the setting.

**Comment by MitchellGerdisch** [comment]
Review stacks work now.
The decision currently is that instead of always enabling review stacks, after you NPW a stack, you can manually set the slider for review stacks (`Use this stack as a template for pull request stacks`) on the Settings->Deploy page.
This setting will be maintained on update.
